# DevOps Configuration File

[exclude]
#buggy_cpp_macros = []

[logging]
#global_level = "INFO"
#utils_level = "INFO"
#config_level = "INFO"
#cpp_level = "INFO"

[git]
#tag_prefix = ""
#empty_tag_list_allowed = true

[cpp]
#style_checks = true
#license_header_check = true
#license_header = <some file path>
#check_only_staged_files = false
#header_guards_according_to_filepath = false

[file]
#encoding = "utf-8"
changelog_paths = ["CHANGELOG.md", "DEV-CHANGELOG.md"]
#default_changelog_path = "CHANGELOG.md"

